version: '3.7'

services:

  currency-exchange-service:
    image: fidelisfelipe/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - EUREKA.CLIENT.FETCHREGISTRY=true
      - spring.zipkin.baseUrl=http://zipkin-server:9411
    networks:
      - currency-network
    depends_on:
      - naming-server
      - api-gateway-server

  currency-conversion-service:
    image: fidelisfelipe/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - EUREKA.CLIENT.FETCHREGISTRY=true
      - spring.zipkin.baseUrl=http://zipkin-server:9411
    networks:
      - currency-network
    depends_on:
      - naming-server
      - currency-exchange-service

  limits-service:
    image: fidelisfelipe/limits-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - EUREKA.CLIENT.FETCHREGISTRY=true
#      - spring.zipkin.baseUrl=http://zipkin-server:9411
      - spring.cloud.config.uri=http://config-server-service:8888
    networks:
      - currency-network
    depends_on:
      - naming-server
      - config-server

  config-server:
    image: fidelisfelipe/config-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - currency-network
    depends_on:
      - api-gateway-server

  naming-server:
    image: fidelisfelipe/naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
    depends_on:
      - api-gateway-server

  api-gateway-server:
    image: fidelisfelipe/api-gateway-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - EUREKA.CLIENT.FETCHREGISTRY=true
      - spring.zipkin.baseUrl=http://zipkin-server:9411
    networks:
      - currency-network

  workflow:
    image: fidelisfelipe/workflow:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8200:8200"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - EUREKA.CLIENT.FETCHREGISTRY=true
      - spring.zipkin.baseUrl=http://zipkin-server:9411

  zipkin-server:
    image: openzipkin/zipkin:2.24
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

networks:
  currency-network: